### ISSUE TITLE
Delete problem in the sql tab

### ISSUE THREAD

**Issue by mnothic** [xzilla/phppgadmin#11]
SQL error:

ERROR:  syntax error at or near "FROM"
LINE 1: SELECT COUNT(*) AS total FROM (DELETE FROM "Member" WHERE id...
                                              ^

In statement:
SELECT COUNT(*) AS total FROM (DELETE FROM "Member" WHERE id='08f7e420-2ec0-11e4-8887-19bea4760cfa') AS sub

PostgreSQL don't allow nested delete into the SELECT

**Comment by xzilla** [comment]
This is a known / duplicate issue, so closing here, but thanks for the report.
